# Generated by Django 5.1 on 2024-08-18 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('TRANSPORT', 'Transport'), ('ENTRETAIMENT', 'Entretaiment'), ('HEALTH', 'Health'), ('HOUSING', 'Housing'), ('EDUCATION', 'Education'), ('TRAVEL', 'Travel'), ('GIFTS', 'Gifts'), ('SAVINGS', 'Savings'), ('PETS', 'Pets'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
