# Generated by Django 5.1 on 2024-08-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_created_at_alter_expense_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('transport', 'Transport'), ('entretaiment', 'Entretaiment'), ('health', 'Health'), ('housing', 'Housing'), ('education', 'Education'), ('travel', 'Travel'), ('gifts', 'Gifts'), ('savings', 'Savings'), ('pets', 'Pets'), ('other', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateField(),
        ),
    ]
