
POST http://localhost:8000/api/auth/signup/ 
Content-Type: application/json

{ "username": "hanzeel", "password": "userPassword1" }

###

POST http://localhost:8000/api/auth/login/ 
Content-Type: application/json

{ "username": "hanzeel", "password": "userPassword1" }

###

POST http://localhost:8000/api/auth/logout/
Authorization: token 1c5b388872511fb5126b9f04438d50e1b5580c6c 